ci: debug vscode marketplace workflow (#302)

diff --git a/.github/workflows/deploy_release_to_marketplace.yml b/.github/workflows/deploy_release_to_marketplace.yml
--- a/.github/workflows/deploy_release_to_marketplace.yml
+++ b/.github/workflows/deploy_release_to_marketplace.yml
@@ -29,11 +29,16 @@ jobs:
       - name: Download and prepare release vsix from GitHub repository
         run: |
           DOWNLOAD_URL=$(curl -sH "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/autokitteh/vscode-extension/releases/tags/${{ github.event.inputs.tag }}" | jq -r '.assets[] | select(.name | endswith(".vsix")).browser_download_url')
+          echo "DOWNLOAD_URL: $DOWNLOAD_URL"
           if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
             echo "Error: No asset found for download or failed to parse URL."
             exit 1
           fi
           curl -sLJO -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -o extension.vsix "$DOWNLOAD_URL"
+          if [ ! -f "extension.vsix" ]; then
+            echo "Error: Failed to download extension.vsix"
+            exit 1
+          fi
 
       - name: Publish to VSCode Marketplace
         run: |
