refactor: fix the flow after tests

diff --git a/.github/workflows/deploy_release_to_marketplace.yml b/.github/workflows/deploy_release_to_marketplace.yml
--- a/.github/workflows/deploy_release_to_marketplace.yml
+++ b/.github/workflows/deploy_release_to_marketplace.yml
@@ -16,46 +16,31 @@ on:
         required: true
 
 jobs:
-  publish-pre-release-to-marketplace:
-    name: Publish Pre-Release to VSCode Marketplace
-    if: github.event.inputs.release-type == 'pre-release'
+  publish-to-marketplace:
+    name: Publish to VSCode Marketplace
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.inputs.tag }}
-          token: ${{ secrets.PAT_TOKEN }}
-          submodules: true
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
         with:
           node-version: "21.2.0"
           cache: "npm"
 
-      - name: Build from scratch pre-release extension version
+      - name: Download and prepare release vsix from GitHub repository
         run: |
-          git submodule update --remote
-          npm ci
-          npm run compile:all
-          npm run build:all
-
-      - name: Publish to VSCode Marketplace as pre-release
-        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --pre-release
-
-  publish-to-marketplace:
-    name: Publish to VSCode Marketplace
-    if: github.event.inputs.release-type == 'release'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download and prepare release vsix from github repository
-        uses: dsaltares/fetch-gh-release-asset@master
-        with:
-          version: tags/${{ github.event.inputs.tag }}
-          file: autokitteh-${{ github.event.inputs.tag }}.vsix
-          target: extension.vsix
-          token: ${{ secrets.PAT_TOKEN }}
-
+          DOWNLOAD_URL=$(curl -sH "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/RonenMars/vscode-playground/releases/tags/${{ github.event.inputs.tag }}" | jq -r '.assets[] | select(.name | endswith(".vsix")).browser_download_url')
+          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
+            echo "Error: No asset found for download or failed to parse URL."
+            exit 1
+          fi
+          curl -sLJO -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -o extension.vsix "$DOWNLOAD_URL"
       - name: Publish to VSCode Marketplace
-        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath extension.vsix
+        run: |
+          VSCE_OPTIONS="--packagePath extension.vsix"
+          if [ "${{ github.event.inputs.release-type }}" == "pre-release" ]; then
+            VSCE_OPTIONS="$VSCE_OPTIONS --pre-release"
+          fi
+          echo "Running vsce publish with options: $VSCE_OPTIONS"
+          npx vsce publish -p ${{ secrets.VSCE_TOKEN }} $VSCE_OPTIONS
+        env:
+          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
